spring:
  datasource:
    url: jdbc:mysql://localhost:3306/couchsurfers
    username: root
    password: asdQWE123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true